name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_svg: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: res/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300

        - asset: res/fonts/Roboto/Roboto-Regular.ttf
        - asset: res/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

        - asset: res/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: res/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900