/// Constant app icons
class AppIcons {
  static String go = "assets/icons/Go.svg",
      union = "assets/icons/Union.svg",
      bucket = "assets/icons/Bucket.svg",
      view = "assets/icons/View.svg",
      subtract = "assets/icons/Subtract.svg",
      tick = "assets/icons/Tick.svg",
      info = "assets/icons/Info.svg",
      calendar = "assets/icons/Calendar.svg",
      heart = "assets/icons/Heart.svg",
      plus = "assets/icons/Plus.svg",
      delete = "assets/icons/Delete.svg",
      search = "assets/icons/Search.svg",
      list = "assets/icons/List.svg",
      map = "assets/icons/Map.svg",
      heartFull = "assets/icons/Heart_full.svg",
      settings = "assets/icons/Settings.svg",
      card = "assets/icons/Card.svg",
      filter = "assets/icons/Filter.svg",
      share = "assets/icons/Share.svg",
      arrow = "assets/icons/Arrow.svg",
      close = "assets/icons/Close.svg",
      hotel = "assets/icons/categories/Hotel.svg",
      restourant = "assets/icons/categories/Restourant.svg",
      particularPlace = "assets/icons/categories/Particular_place.svg",
      park = "assets/icons/categories/Park.svg",
      museum = "assets/icons/categories/Museum.svg",
      cafe = "assets/icons/categories/Cafe.svg",
      pointer = "assets/icons/tutorial/Pointer.svg",
      backpack = "assets/icons/tutorial/Backpack.svg",
      clickerFinger = "assets/icons/tutorial/ClickerFinger.svg",
      splashIcon = "assets/icons/SplashIcon.svg",
      file = "assets/icons/File.svg",
      camera = "assets/icons/Camera.svg",
      photo = "assets/icons/Photo.svg";
}
