import 'package:places/ui/screen/settings_screen.dart';

class AppTextStrings {
  static String appBarTitle = "Список\nинтересных мест",
      ploteRouteButton = "построить маршрут",
      planningButton = "Запланировать",
      favoritesButton = "В избранное",
      visitingScreenTitle = "Избранное",
      scheduledDate = "Запланировано на 15 окт. 2020",
      goalAchieved = "Цель достигнута 12 окт. 2020",
      toVisitTab = "Посетил",
      visitedTab = "Хочу посетить",
      emptyPageTitle = "Пусто",
      emptyPageSubtitle =
          "Отмечайте понравившиеся места\nи они появиятся здесь.",
      emptyPageSubtitleVisited = "Завершите маршрут,\nчтобы место попало сюда.",
      bottomNavigationBarLabelList = "Интересные места",
      bottomNavigationBarLabelMap = "Карта",
      bottomNavigationBarLabelFavorites = "Избранное",
      bottomNavigationBarLabelSettings = "Настройки",
      filterScreenClearButton = "Очистить",
      fiterScreenTitleText = "Категории",
      filterScreenSliderTitle = "Расстояние",
      filterScreenSliderRangeFrom = "от ",
      filterScreenSliderRangeUntil = " до ",
      filterScreenSliderRangeUnit = " м",
      filterScreenShowButton = "Показать",
      hotel = "Отель",
      restourant = "Ресторан",
      particularPlace = "Особое место",
      park = "Парк",
      museum = "Музей",
      cafe = "Кафе",
      settingsScreenTitle = "Настройки",
      settingsScreenEnableDarkTheme = "Тёмная тема",
      settingsScreenWatchTutorial = "Смотреть туториал";
}
