/// Constant application text strings
class AppTextStrings {
  static String appBarTitle = "Список\nинтересных мест",
      appBarMiniTitle = "Список интересных мест",
      ploteRouteButton = "построить маршрут",
      planningButton = "Запланировать",
      favoritesButton = "В избранное",
      visitingScreenTitle = "Избранное",
      delete = "Удалить",
      scheduledDate = "Запланировано на 15 окт. 2020",
      goalAchieved = "Цель достигнута 12 окт. 2020",
      toVisitTab = "Посетил",
      visitedTab = "Хочу посетить",
      emptyPageTitle = "Пусто",
      emptyPageSubtitle =
          "Отмечайте понравившиеся места\nи они появиятся здесь.",
      emptyPageSubtitleVisited = "Завершите маршрут,\nчтобы место попало сюда.",
      bottomNavigationBarLabelList = "Интересные места",
      bottomNavigationBarLabelMap = "Карта",
      bottomNavigationBarLabelFavorites = "Избранное",
      bottomNavigationBarLabelSettings = "Настройки",
      filterScreenClearButton = "Очистить",
      fiterScreenTitleText = "Категории",
      filterScreenSliderTitle = "Расстояние",
      filterScreenSliderRangeFrom = "от ",
      filterScreenSliderRangeUntil = " до ",
      filterScreenSliderRangeUnit = " м",
      filterScreenShowButton = "Показать",
      hotel = "Отель",
      restourant = "Ресторан",
      particularPlace = "Особое место",
      park = "Парк",
      museum = "Музей",
      cafe = "Кафе",
      settingsScreenTitle = "Настройки",
      settingsScreenEnableDarkTheme = "Тёмная тема",
      settingsScreenWatchTutorial = "Смотреть туториал",
      addSightScreenTitle = "Новое место",
      addSightScreenCategoryLabel = "Категория",
      addSightScreenCancelButton = "Отмена",
      addSightScreenTextFormFieldNotSelected = "Не выбрано",
      addSightScreenTextFormFieldNotSpecified = "Не указано",
      addSightScreenTextFormFieldEmpty = "Введите текст",
      addSightScreenSightNameLabel = "Название",
      addSightScreenSightLatitudeLabel = "Широта",
      addSightScreenSightLongitudeLabel = "Долгота",
      addSightScreenSightSpecifyCoordinates = "Указать на карте",
      addSightScreenSightDescriptionLabel = "Описание",
      addSightScreenSightCreateButton = "Создать",
      appBarCustomCancelButton = "Отмена",
      selectingSightTypeScreenTitle = "Категория",
      selectingSightTypeScreenSaveButton = "Сохранить",
      createSightButton = "Новое место",
      searchBarHintText = "Поиск",
      sightSearchScreenSearchHistory = "Вы искали",
      sightSearchScreenCleanHistory = "Очистить историю",
      sightsNotFoundTitle = "Ничего не найдено",
      sightsNotFoundSubtitle = "Попробуйте изменить параметры поиска",
      onBoardingSkipButton = "Пропустить",
      onBoardingFirstPageTitle = "Добро пожаловать в Путеводитель",
      onBoardingFirstPageSubtitle =
          "Ищи новые локации и сохраняй самые любимые.",
      onBoardingSecondPageTitle = "Построй маршрут и отправляйся в путь",
      onBoardingSecondPageSubtitle =
          "Достигай цели максимально быстро и комфортно.",
      onBoardingThirdPageTitle = "Добавляй места, которые нашёл сам",
      onBoardingThirdPageSubtitle =
          "Делись самыми интересными и помоги нам стать лучше!",
      onBoardingStartButton = "На старт";
}
