/// Constant application text strings
class AppTextStrings {
  static String appTitle = "Places",
      appBarTitle = "Список\nинтересных мест",
      appBarMiniTitle = "Список интересных мест",
      ploteRouteButton = "построить маршрут",
      planningButton = "Запланировать",
      favoritesButtonInactive = "В избранное",
      favoritesButtonActive = "В избранном",
      visitingScreenTitle = "Избранное",
      delete = "Удалить",
      scheduledDate = "Запланировано на 15 окт. 2020",
      goalAchieved = "Цель достигнута 12 окт. 2020",
      toVisitTab = "Посетил",
      visitedTab = "Хочу посетить",
      emptyPageTitle = "Пусто",
      emptyPageSubtitleDefault =
          "Попробуйте обновить страницу\nили зайдите позже.",
      emptyPageSubtitleVisited = "Завершите маршрут,\nчтобы место попало сюда.",
      emptyPageSubtitleUnvisited =
          "Отмечайте понравившиеся места\nи они появиятся здесь.",
      dataLoadingErrorTitle = "Ошибка",
      dataLoadingErrorSubtitle = "Что то пошло не так.\nПопробуйте позже.",
      bottomNavigationBarLabelList = "Интересные места",
      bottomNavigationBarLabelMap = "Карта",
      bottomNavigationBarLabelFavorites = "Избранное",
      bottomNavigationBarLabelSettings = "Настройки",
      filterScreenClearButton = "Очистить",
      fiterScreenTitleText = "Категории",
      filterScreenSliderTitle = "Расстояние",
      filterScreenSliderRangeFrom = "от ",
      filterScreenSliderRangeUntil = " до ",
      filterScreenSliderRangeUnit = " м",
      filterScreenShowButton = "Показать",
      cardWidgetDistanceToPlace = " км до места",
      hotel = "Отель",
      restourant = "Ресторан",
      particularPlace = "Особое место",
      park = "Парк",
      museum = "Музей",
      cafe = "Кафе",
      settingsScreenTitle = "Настройки",
      settingsScreenEnableDarkTheme = "Тёмная тема",
      settingsScreenWatchTutorial = "Смотреть туториал",
      addPlaceScreenTitle = "Новое место",
      addPlaceScreenCategoryLabel = "Категория",
      addPlaceScreenCancelButton = "Отмена",
      addPlaceScreenAddPhotoDialogCancelButton = "Отмена",
      addPlaceScreenTextFormFieldNotSelected = "Не выбрано",
      addPlaceScreenTextFormFieldNotSpecified = "Не указано",
      addPlaceScreenTextFormFieldEmpty = "Введите текст",
      addPlaceScreenPlaceNameLabel = "Название",
      addPlaceScreenPlaceLatitudeLabel = "Широта",
      addPlaceScreenPlaceLongitudeLabel = "Долгота",
      addPlaceScreenPlaceSpecifyCoordinates = "Указать на карте",
      addPlaceScreenPlaceDescriptionLabel = "Описание",
      addPlaceScreenPlaceCreateButton = "Создать",
      addPlaceScreenAddPhotoDialogButtonFile = "Файл",
      addPlaceScreenAddPhotoDialogButtonCamera = "Камера",
      addPlaceScreenAddPhotoDialogButtonPhoto = "Фото",
      appBarCustomCancelButton = "Отмена",
      selectingPlaceTypeScreenTitle = "Категория",
      selectingPlaceTypeScreenSaveButton = "Сохранить",
      createPlaceButton = "Новое место",
      searchBarHintText = "Поиск",
      placeSearchScreenSearchHistory = "Вы искали",
      placeSearchScreenCleanHistory = "Очистить историю",
      placesNotFoundTitle = "Ничего не найдено",
      placesNotFoundSubtitle = "Попробуйте изменить параметры поиска",
      onBoardingSkipButton = "Пропустить",
      onBoardingFirstPageTitle = "Добро пожаловать в Путеводитель",
      onBoardingFirstPageSubtitle =
          "Ищи новые локации и сохраняй самые любимые.",
      onBoardingSecondPageTitle = "Построй маршрут и отправляйся в путь",
      onBoardingSecondPageSubtitle =
          "Достигай цели максимально быстро и комфортно.",
      onBoardingThirdPageTitle = "Добавляй места, которые нашёл сам",
      onBoardingThirdPageSubtitle =
          "Делись самыми интересными и помоги нам стать лучше!",
      onBoardingStartButton = "На старт",
      datePickerHelpText = "Выбрать дату",
      datePickerConfrimText = "Подтвердить",
      datePickerCancelText = "Отмена";
}
